version: '3.1'

services:
  php:
    build: 
      context: .
    #image: firli/responsi-cloud-s5_php:firstpush
    ports:
      - 80:80
    volumes:
      - ./html:/var/www/html/

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./html:/docker-entrypoint-initdb.d

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
